#!/bin/bash
echo "Welcome to Hashbrownies, a simple tool for generating and scanning checksum files."
echo "This software is licensed under GPL v3 and is provided as-is with no guarantee of suitability for a particular purpose. Use at your own risk."
echo ""
